version: 2.1
orbs:
  node: circleci/node@2.1.1
jobs:
  build-and-deploy:
    executor:
      name: node/default
    steps:
      - checkout
      - run: npm install
      - run: npm run build
      - deploy:
          command: bash .circleci/compile.sh
workflows:
    build-and-deploy:
      jobs:
        - build-and-deploy:
            filters:
              branches:
                only:
                  - master